
OpenDatabase("localhost:/Users/gmurphy/Downloads/snoopy6/data/v*.vtk database", 0)
SetWindowLayout(6)
SetActiveWindow(1)
AddPlot("Pseudocolor", "vx", 1, 1)
ToggleLockTime()
ToggleLockViewMode()
DrawPlots()
SetActiveWindow(2)
AddPlot("Pseudocolor", "vy", 1, 1)
ToggleLockTime()
ToggleLockViewMode()
DrawPlots()
SetActiveWindow(3)
AddPlot("Pseudocolor", "vz", 1, 1)
ToggleLockTime()
ToggleLockViewMode()
DrawPlots()
SetActiveWindow(4)
AddPlot("Pseudocolor", "bx", 1, 1)
ToggleLockTime()
ToggleLockViewMode()
DrawPlots()
SetActiveWindow(5)
AddPlot("Pseudocolor", "by", 1, 1)
ToggleLockTime()
ToggleLockViewMode()
DrawPlots()
SetActiveWindow(6)
AddPlot("Pseudocolor", "bz", 1, 1)
ToggleLockTime()
ToggleLockViewMode()
DrawPlots()
